import { FaHome, FaStoreAlt, FaUserCog } from 'react-icons/fa'
import { FaPeopleRoof } from 'react-icons/fa6'
import { MdAcUnit, MdDevices, MdAssessment } from 'react-icons/md'
import { TbUsers } from 'react-icons/tb'
import {
  Dashboard,
  ReportsList,
  BranchesCreate,
  BranchesEdit,
  BranchesList,
  LocationsCreate,
  LocationsList,
  LocationsEdit,
  CustomersCreate,
  CustomersEdit,
  CustomersList,
  DevicesCreate,
  DevicesEdit,
  DevicesList,
  RolesCreate,
  RolesEdit,
  RolesList,
  UsersCreate,
  UsersEdit,
  UsersList,
  Login,
} from './pages'

export const routes = [
  {
    to: '/dashboard',
    icon: <FaHome />,
    label: 'Ana Sayfa',
    isSidebarPage: true,
    element: <Dashboard />,
  },
  {
    to: '/customers',
    icon: <FaPeopleRoof />,
    label: 'Müşteriler',
    isSidebarPage: true,
    element: <CustomersList />,
  },
  {
    to: '/customers/create',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <CustomersCreate />,
  },
  {
    to: '/customers/:id/edit',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <CustomersEdit />,
  },
  {
    to: '/branches',
    icon: <FaStoreAlt />,
    label: 'Şubeler',
    isSidebarPage: true,
    element: <BranchesList />,
  },
  {
    to: '/branches/create',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <BranchesCreate />,
  },
  {
    to: '/branches/:id/edit',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <BranchesEdit />,
  },
  {
    to: '/users',
    icon: <TbUsers />,
    label: 'Kullanıcılar',
    isSidebarPage: true,
    element: <UsersList />,
  },
  {
    to: '/users/create',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <UsersCreate />,
  },
  {
    to: '/users/:id/edit',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <UsersEdit />,
  },
  {
    to: '/locations',
    icon: <MdAcUnit />,
    label: 'Lokasyonlar',
    isSidebarPage: true,
    element: <LocationsList />,
  },
  {
    to: '/locations/create',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <LocationsCreate />,
  },
  {
    to: '/locations/:id/edit',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <LocationsEdit />,
  },
  {
    to: '/devices',
    icon: <MdDevices />,
    label: 'Cihazlar',
    isSidebarPage: true,
    element: <DevicesList />,
  },
  {
    to: '/devices/create',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <DevicesCreate />,
  },
  {
    to: '/devices/:id/edit',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <DevicesEdit />,
  },
  {
    to: '/roles',
    icon: <FaUserCog />,
    label: 'Roller',
    isSidebarPage: true,
    element: <RolesList />,
  },
  {
    to: '/roles/create',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <RolesCreate />,
  },
  {
    to: '/roles/:id/edit',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <RolesEdit />,
  },
  {
    to: '/reports',
    icon: <MdAssessment />,
    label: 'Raporlar',
    isSidebarPage: true,
    element: <ReportsList />,
  },
  {
    to: '/login',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <Login />,
  },
]