import { FaHome } from "react-icons/fa"
import {
  Dashboard,
  ReportsList,
  BranchesCreate,
  BranchesEdit,
  BranchesList,
  ClimatesCreate,
  ClimatesList,
  ClimatesEdit,
  CustomersCreate,
  CustomersEdit,
  CustomersList,
  DevicesCreate,
  DevicesEdit,
  DevicesList,
  RolesCreate,
  RolesEdit,
  RolesList,
  UsersCreate,
  UsersEdit,
  UsersList,
} from './pages'

export const routes = [
  {
    to: '/dashboard',
    icon: <FaHome />,
    label: 'Ana Sayfa',
    isSidebarPage: true,
    element: <Dashboard />,
  },
  {
    to: '/branches',
    icon: <FaHome />,
    label: 'Şubeler',
    isSidebarPage: true,
    element: <BranchesList />,
  },
  {
    to: '/branches/create',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <BranchesCreate />,
  },
  {
    to: '/branches/:id/edit',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <BranchesEdit />,
  },
  {
    to: '/climates',
    icon: <FaHome />,
    label: 'Klimalar',
    isSidebarPage: true,
    element: <ClimatesList />,
  },
  {
    to: '/climates/create',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <ClimatesCreate />,
  },
  {
    to: '/climates/:id/edit',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <ClimatesEdit />,
  },
  {
    to: '/customers',
    icon: <FaHome />,
    label: 'Müşteriler',
    isSidebarPage: true,
    element: <CustomersList />,
  },
  {
    to: '/customers/create',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <CustomersCreate />,
  },
  {
    to: '/customers/:id/edit',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <CustomersEdit />,
  },
  {
    to: '/devices',
    icon: <FaHome />,
    label: 'Cihazlar',
    isSidebarPage: true,
    element: <DevicesList />,
  },
  {
    to: '/devices/create',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <DevicesCreate />,
  },
  {
    to: '/devices/:id/edit',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <DevicesEdit />,
  },
  {
    to: '/users',
    icon: <FaHome />,
    label: 'Kullanıcılar',
    isSidebarPage: true,
    element: <UsersList />,
  },
  {
    to: '/users/create',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <UsersCreate />,
  },
  {
    to: '/users/:id/edit',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <UsersEdit />,
  },
  {
    to: '/roles',
    icon: <FaHome />,
    label: 'Roller',
    isSidebarPage: true,
    element: <RolesList />,
  },
  {
    to: '/roles/create',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <RolesCreate />,
  },
  {
    to: '/roles/:id/edit',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <RolesEdit />,
  },
  // {
  //   to: '/reports',
  //   icon: <FaHome />,
  //   label: 'Raporlar',
  //   isSidebarPage: true,
  //   element: <ReportsList />,
  // },
]