import { FaHome } from "react-icons/fa"
import {
  Dashboard,
  ReportsList,
  BranchesCreate,
  BranchesEdit,
  BranchesList,
  ClimatesCreate,
  ClimatesList,
  ClimatesEdit,
  CustomersCreate,
  CustomersEdit,
  CustomersList,
} from './pages'

export const routes = [
  {
    to: '/dashboard',
    icon: <FaHome />,
    label: 'Ana Sayfa',
    isSidebarPage: true,
    element: <Dashboard />,
  },
  {
    to: '/branches',
    icon: <FaHome />,
    label: 'Şubeler',
    isSidebarPage: true,
    element: <BranchesList />,
  },
  {
    to: '/branches/create',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <BranchesCreate />,
  },
  {
    to: '/branches/:id/edit',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <BranchesEdit />,
  },
  {
    to: '/climates',
    icon: <FaHome />,
    label: 'Klimalar',
    isSidebarPage: true,
    element: <ClimatesList />,
  },
  {
    to: '/climates/create',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <ClimatesCreate />,
  },
  {
    to: '/climates/:id/edit',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <ClimatesEdit />,
  },
  {
    to: '/customers',
    icon: <FaHome />,
    label: 'Müşteriler',
    isSidebarPage: true,
    element: <CustomersList />,
  },
  {
    to: '/customers/create',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <CustomersCreate />,
  },
  {
    to: '/customers/:id/edit',
    icon: null,
    label: null,
    isSidebarPage: false,
    element: <CustomersEdit />,
  },
  {
    to: '/reports',
    icon: <FaHome />,
    label: 'Raporlar',
    isSidebarPage: true,
    element: <ReportsList />,
  },
]